# Herald.lol Dependabot Configuration

version: 2
updates:
  # Backend Go dependencies
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "senior-backend"
      - "lead-dev"
    labels:
      - "dependencies"
      - "backend"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "senior-frontend"
      - "lead-dev"
    labels:
      - "dependencies"
      - "frontend"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major React updates - review manually
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    groups:
      react-dependencies:
        patterns:
          - "react*"
          - "@types/react*"
      testing-dependencies:
        patterns:
          - "*jest*"
          - "*cypress*"
          - "@testing-library/*"
      mui-dependencies:
        patterns:
          - "@mui/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "devops-lead"
      - "lead-dev"
    labels:
      - "dependencies"
      - "ci/cd"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"
    reviewers:
      - "devops-lead"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    reviewers:
      - "devops-lead"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "build"
      include: "scope"