version: "3.8"

services:
  lol-exporter:
    build:
      context: .
      dockerfile: Dockerfile.production
      target: production
    container_name: lol-exporter-production
    restart: unless-stopped
    environment:
      - GIN_MODE=release
      - LOG_LEVEL=info
      - CORS_ORIGINS=https://herald.lol
      - JWT_SECRET=${JWT_SECRET:-dev-secret-change-in-production}
      - DB_CONNECTION=sqlite:///app/data/lol_matches_production.db
      - WEBHOOK_TIMEOUT=30s
      - MAX_REQUEST_SIZE=10MB
      - REQUEST_TIMEOUT=30s
    ports:
      - "8080:8000"
    networks:
      - lol-production
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:alpine
    container_name: lol-nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - lol-production
    depends_on:
      - lol-exporter

networks:
  lol-production:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  production-data:
    driver: local
  production-exports:
    driver: local
  production-logs:
    driver: local
