version: "3.8"

services:
  lol-fullstack:
    build:
      context: .
      dockerfile: Dockerfile.simple-fullstack
    container_name: lol-fullstack-app
    restart: unless-stopped
    environment:
      - GIN_MODE=release
      - LOG_LEVEL=info
      - CORS_ORIGINS=https://herald.lol,http://herald.lol
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.5"

networks:
  default:
    driver: bridge
