# Horizontal Pod Autoscaler for Blue Environment
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: herald-gaming-analytics-blue-hpa
  namespace: herald-blue
  labels:
    app: herald-gaming-analytics
    version: blue
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: herald-gaming-analytics-blue
  minReplicas: 3
  maxReplicas: 20
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics for gaming analytics performance
  - type: Pods
    pods:
      metric:
        name: gaming_analytics_response_time_ms
      target:
        type: AverageValue
        averageValue: "4000"  # Scale if response time > 4s (target is <5s)
  - type: Pods
    pods:
      metric:
        name: gaming_analytics_requests_per_second
      target:
        type: AverageValue
        averageValue: "50"    # Scale if RPS > 50 per pod
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 4
        periodSeconds: 30
---
# Horizontal Pod Autoscaler for Green Environment
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: herald-gaming-analytics-green-hpa
  namespace: herald-green
  labels:
    app: herald-gaming-analytics
    version: green
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: herald-gaming-analytics-green
  minReplicas: 3
  maxReplicas: 20
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics for gaming analytics performance
  - type: Pods
    pods:
      metric:
        name: gaming_analytics_response_time_ms
      target:
        type: AverageValue
        averageValue: "4000"  # Scale if response time > 4s (target is <5s)
  - type: Pods
    pods:
      metric:
        name: gaming_analytics_requests_per_second
      target:
        type: AverageValue
        averageValue: "50"    # Scale if RPS > 50 per pod
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 4
        periodSeconds: 30