apiVersion: apps/v1
kind: Deployment
metadata:
  name: herald-api
  namespace: herald
  labels:
    app: herald-api
    component: backend
    platform: gaming-analytics
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: herald-api
      component: backend
  template:
    metadata:
      labels:
        app: herald-api
        component: backend
        platform: gaming-analytics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: herald-api
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: herald-api
        image: ghcr.io/herald/herald-api:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: grpc
          containerPort: 9090
          protocol: TCP
        - name: metrics
          containerPort: 9091
          protocol: TCP
        env:
        - name: ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: GRPC_PORT
          value: "9090"
        - name: METRICS_PORT
          value: "9091"
        - name: LOG_LEVEL
          value: "info"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: herald-database
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: herald-redis
              key: url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: herald-jwt
              key: secret
        - name: RIOT_API_KEY
          valueFrom:
            secretKeyRef:
              name: herald-riot
              key: api-key
        - name: RIOT_RATE_LIMIT
          value: "100"
        - name: RIOT_RATE_WINDOW
          value: "120"
        - name: ANALYTICS_TIMEOUT
          value: "5s"
        - name: MAX_CONCURRENT_ANALYTICS
          value: "100"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /startup
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: config
          mountPath: /etc/herald
          readOnly: true
        - name: cache
          mountPath: /tmp/cache
      volumes:
      - name: config
        configMap:
          name: herald-api-config
      - name: cache
        emptyDir:
          sizeLimit: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - herald-api
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: herald-api
---
apiVersion: v1
kind: Service
metadata:
  name: herald-api
  namespace: herald
  labels:
    app: herald-api
    component: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: grpc
    protocol: TCP
  - name: metrics
    port: 9091
    targetPort: metrics
    protocol: TCP
  selector:
    app: herald-api
    component: backend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: herald-api
  namespace: herald
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: herald-api
  minReplicas: 3
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: herald_api_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 5
        periodSeconds: 30
      selectPolicy: Max
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: herald-api
  namespace: herald
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: herald-api
      component: backend