apiVersion: v1
kind: Namespace
metadata:
  name: herald
  labels:
    app: herald
    platform: gaming-analytics
    game: league-of-legends
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: herald-quota
  namespace: herald
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: herald-limits
  namespace: herald
spec:
  limits:
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    type: Container
  - max:
      storage: "100Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim